# Generated by Django 4.0.6 on 2022-07-21 02:05

from django.db import migrations

from articles.models import Status

def populate_sections(apps, schemaeditor):
    section={
        "font-page": "Front page articles (headliner)",
        "sport": "Sport related content",
        "business": "Business related content",
        "society": "society related content",
        "politics": "Politics related content",
    }
    Section = apps.get_model("articles", "Section")
    for name, desc in section.items():
        section_obj = Section(name=name, description = desc)
        section_obj.save()
    

def populate_article_types(apps, schemaeditor):
    art_types={
        "article": "Original research manuscripts",
        "brief_report":"Short, observational studies",
        "editorial":"Opinion piece",
        "column":"An opinionated piece on specific topic",
    }
    ArticleType= apps.get_model("articles", "ArticleType")
    for name, desc in art_types.items():
        art_obj= ArticleType(name=name, description=desc)
        art_obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(populate_article_types),
        migrations.RunPython(populate_sections),
        
    ]
