# Generated by Django 4.0.6 on 2022-07-21 00:33

from django.db import migrations

from accounts.models import Department


def populate_roles(apps, schemaeditor):
    roles ={
        "reader":"A reader of the newspaper",
        "journalist":" A user that work for newspapaer",
        "editor":"A person tasked with reviewing journalist work prior to publishing"
    }
    Role= apps.get_model("accounts", "Role")
    for name, desc in roles.items():
        role_obj= Role(name=name, description=desc)
        role_obj.save()

def populate_departments(apps, schemaeditor):
    department = {
        "front-page" : "A department tasked with writing front page articles",
        "sports": "A department tasked with writing  sport articles",
        "society": "A department tasked with writing  society related articles",
        "business":"A department tasked with writing  business related articles",
        "politics": "A department tasked with writing  politics related articles",
        "classifields": "A department tasked with  reviewing and publishing classifield ads"
    }
    Department= apps.get_model("accounts","Department")
    for name, desc in department.items():
        dept_obj= Department(name=name, description=desc)
        dept_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_departments),
        migrations.RunPython(populate_roles),

    ]

